version: '2'
services:
  hsql:
    image: simple_deployment_hsql
    volumes:
      - ./state/hsql:/opt/hsqldb/data
  platform_admin_init:
    image: simple_deployment_platform
    command: admin initialize
    environment:
      - WAIT_FOR=hsql:9090
    depends_on:
      - hsql
    volumes:
      - ./resources/secrets/:/etc/ssl/certs/hybris
      - ./state/media:/opt/hybris/data/media
