//
// HYBAddressValidation.m
// [y] hybris Platform
//
// Copyright (c) 2000-2016 hybris AG
// All rights reserved.
//
// This software is the confidential and proprietary information of hybris
// ("Confidential Information"). You shall not disclose such Confidential
// Information and shall use it only in accordance with the terms of the
// license agreement you entered into with hybris.
//
// Warning:This file was auto-generated by OCC2Ojbc.
//

#import "HYBAddressValidation.h"
#import "NSValueTransformer+MTLPredefinedTransformerAdditions.h"

#import "HYBAddress.h"


@implementation HYBAddressValidation

+ (instancetype)addressValidationWithParams:(NSDictionary*)params {

NSError *error = nil;
HYBAddressValidation *object = [MTLJSONAdapter modelOfClass:[HYBAddressValidation class] fromJSONDictionary:params error:&error];

if (error) {
    NSLog(@"Couldn't convert JSON to model HYBAddressValidation");
    return nil;
}

return object;
}

+ (NSDictionary *)JSONKeyPathsByPropertyKey {
   return @{
@"errors" : @"errors",
@"decision" : @"decision",
@"suggestedAddresses" : @"suggestedAddresses"
};
}

+ (NSValueTransformer *)errorsJSONTransformer {
return [NSValueTransformer mtl_JSONArrayTransformerWithModelClass:[NSArray class]];
}

+ (NSValueTransformer *)suggestedAddressesJSONTransformer {
return [NSValueTransformer mtl_JSONArrayTransformerWithModelClass:[HYBAddress class]];
}






@end