//
// HYBAbstractOrder.h
// [y] hybris Platform
//
// Copyright (c) 2000-2016 hybris AG
// All rights reserved.
//
// This software is the confidential and proprietary information of hybris
// ("Confidential Information"). You shall not disclose such Confidential
// Information and shall use it only in accordance with the terms of the
// license agreement you entered into with hybris.
//
// Warning:This file was auto-generated by OCC2Ojbc.
//

#import <Foundation/Foundation.h>
#import "MTLModel.h"
#import "MTLJSONAdapter.h"

@class HYBPrice;
@class HYBDeliveryMode;
@class HYBAddress;
@class HYBPrincipal;
@class HYBPaymentDetails;


@interface HYBAbstractOrder : MTLModel <MTLJSONSerializing>

@property (nonatomic) NSArray *appliedProductPromotions;
@property (nonatomic) NSString *code;
@property (nonatomic) HYBPrice *totalPrice;
@property (nonatomic) HYBPrice *totalDiscounts;
@property (nonatomic) HYBPrice *subTotal;
@property (nonatomic) HYBPrice *totalTax;
@property (nonatomic) NSArray *appliedVouchers;
@property (nonatomic) HYBDeliveryMode *deliveryMode;
@property (nonatomic) HYBAddress *deliveryAddress;
@property (nonatomic) NSNumber *deliveryItemsQuantity;
@property (nonatomic) HYBPrice *totalPriceWithTax;
@property (nonatomic) BOOL net;
@property (nonatomic) BOOL calculated;
@property (nonatomic) NSNumber *totalItems;
@property (nonatomic) HYBPrice *productDiscounts;
@property (nonatomic) NSArray *appliedOrderPromotions;
@property (nonatomic) NSArray *pickupOrderGroups;
@property (nonatomic) HYBPrice *orderDiscounts;
@property (nonatomic) NSString *store;
@property (nonatomic) NSArray *entries;
@property (nonatomic) NSString *site;
@property (nonatomic) NSString *guid;
@property (nonatomic) NSNumber *pickupItemsQuantity;
@property (nonatomic) HYBPrincipal *user;
@property (nonatomic) HYBPaymentDetails *paymentInfo;
@property (nonatomic) NSArray *deliveryOrderGroups;
@property (nonatomic) HYBPrice *deliveryCost;


+ (instancetype)abstractOrderWithParams:(NSDictionary*)params;

@end