//
// HYBCategoryHierarchy.m
// [y] hybris Platform
//
// Copyright (c) 2000-2016 hybris AG
// All rights reserved.
//
// This software is the confidential and proprietary information of hybris
// ("Confidential Information"). You shall not disclose such Confidential
// Information and shall use it only in accordance with the terms of the
// license agreement you entered into with hybris.
//
// Warning:This file was auto-generated by OCC2Ojbc.
//

#import "HYBCategoryHierarchy.h"
#import "NSValueTransformer+MTLPredefinedTransformerAdditions.h"

#import "HYBCategoryHierarchy.h"
#import "HYBProduct.h"


@implementation HYBCategoryHierarchy

+ (instancetype)categoryHierarchyWithParams:(NSDictionary*)params {

NSError *error = nil;
HYBCategoryHierarchy *object = [MTLJSONAdapter modelOfClass:[HYBCategoryHierarchy class] fromJSONDictionary:params error:&error];

if (error) {
    NSLog(@"Couldn't convert JSON to model HYBCategoryHierarchy");
    return nil;
}

return object;
}

+ (NSDictionary *)JSONKeyPathsByPropertyKey {
   return @{
@"pageSize" : @"pageSize",
@"totalNumber" : @"totalNumber",
@"currentPage" : @"currentPage",
@"numberOfPages" : @"numberOfPages",
@"subcategories" : @"subcategories",
@"products" : @"products"
};
}

+ (NSValueTransformer *)subcategoriesJSONTransformer {
return [NSValueTransformer mtl_JSONArrayTransformerWithModelClass:[HYBCategoryHierarchy class]];
}

+ (NSValueTransformer *)productsJSONTransformer {
return [NSValueTransformer mtl_JSONArrayTransformerWithModelClass:[HYBProduct class]];
}






@end