//
// HYBCountryList.m
// [y] hybris Platform
//
// Copyright (c) 2000-2016 hybris AG
// All rights reserved.
//
// This software is the confidential and proprietary information of hybris
// ("Confidential Information"). You shall not disclose such Confidential
// Information and shall use it only in accordance with the terms of the
// license agreement you entered into with hybris.
//
// Warning:This file was auto-generated by OCC2Ojbc.
//

#import "HYBCountryList.h"
#import "NSValueTransformer+MTLPredefinedTransformerAdditions.h"

#import "HYBCountry.h"


@implementation HYBCountryList

+ (instancetype)countryListWithParams:(NSDictionary*)params {

NSError *error = nil;
HYBCountryList *object = [MTLJSONAdapter modelOfClass:[HYBCountryList class] fromJSONDictionary:params error:&error];

if (error) {
    NSLog(@"Couldn't convert JSON to model HYBCountryList");
    return nil;
}

return object;
}

+ (NSDictionary *)JSONKeyPathsByPropertyKey {
   return @{
@"countries" : @"countries"
};
}

+ (NSValueTransformer *)countriesJSONTransformer {
return [NSValueTransformer mtl_JSONArrayTransformerWithModelClass:[HYBCountry class]];
}






@end