//
// HYBCardTypeList.m
// [y] hybris Platform
//
// Copyright (c) 2000-2016 hybris AG
// All rights reserved.
//
// This software is the confidential and proprietary information of hybris
// ("Confidential Information"). You shall not disclose such Confidential
// Information and shall use it only in accordance with the terms of the
// license agreement you entered into with hybris.
//
// Warning:This file was auto-generated by OCC2Ojbc.
//

#import "HYBCardTypeList.h"
#import "NSValueTransformer+MTLPredefinedTransformerAdditions.h"

#import "HYBCardType.h"


@implementation HYBCardTypeList

+ (instancetype)cardTypeListWithParams:(NSDictionary*)params {

NSError *error = nil;
HYBCardTypeList *object = [MTLJSONAdapter modelOfClass:[HYBCardTypeList class] fromJSONDictionary:params error:&error];

if (error) {
    NSLog(@"Couldn't convert JSON to model HYBCardTypeList");
    return nil;
}

return object;
}

+ (NSDictionary *)JSONKeyPathsByPropertyKey {
   return @{
@"cardTypes" : @"cardTypes"
};
}

+ (NSValueTransformer *)cardTypesJSONTransformer {
return [NSValueTransformer mtl_JSONArrayTransformerWithModelClass:[HYBCardType class]];
}






@end