//
// HYBCategory.m
// [y] hybris Platform
//
// Copyright (c) 2000-2016 hybris AG
// All rights reserved.
//
// This software is the confidential and proprietary information of hybris
// ("Confidential Information"). You shall not disclose such Confidential
// Information and shall use it only in accordance with the terms of the
// license agreement you entered into with hybris.
//
// Warning:This file was auto-generated by OCC2Ojbc.
//

#import "HYBCategory.h"
#import "NSValueTransformer+MTLPredefinedTransformerAdditions.h"

#import "HYBImage.h"


@implementation HYBCategory

+ (instancetype)categoryWithParams:(NSDictionary*)params {

NSError *error = nil;
HYBCategory *object = [MTLJSONAdapter modelOfClass:[HYBCategory class] fromJSONDictionary:params error:&error];

if (error) {
    NSLog(@"Couldn't convert JSON to model HYBCategory");
    return nil;
}

return object;
}

+ (NSDictionary *)JSONKeyPathsByPropertyKey {
   return @{
@"code" : @"code",
@"url" : @"url",
@"image" : @"image"
};
}




+ (NSValueTransformer *)imageJSONTransformer {
return [NSValueTransformer mtl_JSONDictionaryTransformerWithModelClass:[HYBImage class]];
}



@end