//
// HYBConsignment.m
// [y] hybris Platform
//
// Copyright (c) 2000-2016 hybris AG
// All rights reserved.
//
// This software is the confidential and proprietary information of hybris
// ("Confidential Information"). You shall not disclose such Confidential
// Information and shall use it only in accordance with the terms of the
// license agreement you entered into with hybris.
//
// Warning:This file was auto-generated by OCC2Ojbc.
//

#import "HYBConsignment.h"
#import "NSValueTransformer+MTLPredefinedTransformerAdditions.h"

#import "HYBConsignmentEntry.h"
#import "HYBAddress.h"
#import "HYBPointOfService.h"


@implementation HYBConsignment

+ (instancetype)consignmentWithParams:(NSDictionary*)params {

NSError *error = nil;
HYBConsignment *object = [MTLJSONAdapter modelOfClass:[HYBConsignment class] fromJSONDictionary:params error:&error];

if (error) {
    NSLog(@"Couldn't convert JSON to model HYBConsignment");
    return nil;
}

return object;
}

+ (NSDictionary *)JSONKeyPathsByPropertyKey {
   return @{
@"code" : @"code",
@"trackingID" : @"trackingID",
@"status" : @"status",
@"statusDate" : @"statusDate",
@"entries" : @"entries",
@"shippingAddress" : @"shippingAddress",
@"deliveryPointOfService" : @"deliveryPointOfService"
};
}

+ (NSValueTransformer *)entriesJSONTransformer {
return [NSValueTransformer mtl_JSONArrayTransformerWithModelClass:[HYBConsignmentEntry class]];
}




+ (NSValueTransformer *)shippingAddressJSONTransformer {
return [NSValueTransformer mtl_JSONDictionaryTransformerWithModelClass:[HYBAddress class]];
}

+ (NSValueTransformer *)deliveryPointOfServiceJSONTransformer {
return [NSValueTransformer mtl_JSONDictionaryTransformerWithModelClass:[HYBPointOfService class]];
}



@end