//
// HYBDeliveryModeList.m
// [y] hybris Platform
//
// Copyright (c) 2000-2016 hybris AG
// All rights reserved.
//
// This software is the confidential and proprietary information of hybris
// ("Confidential Information"). You shall not disclose such Confidential
// Information and shall use it only in accordance with the terms of the
// license agreement you entered into with hybris.
//
// Warning:This file was auto-generated by OCC2Ojbc.
//

#import "HYBDeliveryModeList.h"
#import "NSValueTransformer+MTLPredefinedTransformerAdditions.h"

#import "HYBDeliveryMode.h"


@implementation HYBDeliveryModeList

+ (instancetype)deliveryModeListWithParams:(NSDictionary*)params {

NSError *error = nil;
HYBDeliveryModeList *object = [MTLJSONAdapter modelOfClass:[HYBDeliveryModeList class] fromJSONDictionary:params error:&error];

if (error) {
    NSLog(@"Couldn't convert JSON to model HYBDeliveryModeList");
    return nil;
}

return object;
}

+ (NSDictionary *)JSONKeyPathsByPropertyKey {
   return @{
@"deliveryModes" : @"deliveryModes"
};
}

+ (NSValueTransformer *)deliveryModesJSONTransformer {
return [NSValueTransformer mtl_JSONArrayTransformerWithModelClass:[HYBDeliveryMode class]];
}






@end