//
// HYBFacetValue.m
// [y] hybris Platform
//
// Copyright (c) 2000-2016 hybris AG
// All rights reserved.
//
// This software is the confidential and proprietary information of hybris
// ("Confidential Information"). You shall not disclose such Confidential
// Information and shall use it only in accordance with the terms of the
// license agreement you entered into with hybris.
//
// Warning:This file was auto-generated by OCC2Ojbc.
//

#import "HYBFacetValue.h"
#import "NSValueTransformer+MTLPredefinedTransformerAdditions.h"

#import "HYBSearchState.h"


@implementation HYBFacetValue

+ (instancetype)facetValueWithParams:(NSDictionary*)params {

NSError *error = nil;
HYBFacetValue *object = [MTLJSONAdapter modelOfClass:[HYBFacetValue class] fromJSONDictionary:params error:&error];

if (error) {
    NSLog(@"Couldn't convert JSON to model HYBFacetValue");
    return nil;
}

return object;
}

+ (NSDictionary *)JSONKeyPathsByPropertyKey {
   return @{
@"name" : @"name",
@"count" : @"count",
@"query" : @"query",
@"selected" : @"selected"
};
}




+ (NSValueTransformer *)queryJSONTransformer {
return [NSValueTransformer mtl_JSONDictionaryTransformerWithModelClass:[HYBSearchState class]];
}



@end