//
// HYBMemberList.m
// [y] hybris Platform
//
// Copyright (c) 2000-2016 hybris AG
// All rights reserved.
//
// This software is the confidential and proprietary information of hybris
// ("Confidential Information"). You shall not disclose such Confidential
// Information and shall use it only in accordance with the terms of the
// license agreement you entered into with hybris.
//
// Warning:This file was auto-generated by OCC2Ojbc.
//

#import "HYBMemberList.h"
#import "NSValueTransformer+MTLPredefinedTransformerAdditions.h"

#import "HYBPrincipal.h"


@implementation HYBMemberList

+ (instancetype)memberListWithParams:(NSDictionary*)params {

NSError *error = nil;
HYBMemberList *object = [MTLJSONAdapter modelOfClass:[HYBMemberList class] fromJSONDictionary:params error:&error];

if (error) {
    NSLog(@"Couldn't convert JSON to model HYBMemberList");
    return nil;
}

return object;
}

+ (NSDictionary *)JSONKeyPathsByPropertyKey {
   return @{
@"members" : @"members"
};
}

+ (NSValueTransformer *)membersJSONTransformer {
return [NSValueTransformer mtl_JSONArrayTransformerWithModelClass:[HYBPrincipal class]];
}






@end