//
// HYBOrderHistoryList.m
// [y] hybris Platform
//
// Copyright (c) 2000-2016 hybris AG
// All rights reserved.
//
// This software is the confidential and proprietary information of hybris
// ("Confidential Information"). You shall not disclose such Confidential
// Information and shall use it only in accordance with the terms of the
// license agreement you entered into with hybris.
//
// Warning:This file was auto-generated by OCC2Ojbc.
//

#import "HYBOrderHistoryList.h"
#import "NSValueTransformer+MTLPredefinedTransformerAdditions.h"

#import "HYBPagination.h"
#import "HYBOrderHistory.h"
#import "HYBSort.h"


@implementation HYBOrderHistoryList

+ (instancetype)orderHistoryListWithParams:(NSDictionary*)params {

NSError *error = nil;
HYBOrderHistoryList *object = [MTLJSONAdapter modelOfClass:[HYBOrderHistoryList class] fromJSONDictionary:params error:&error];

if (error) {
    NSLog(@"Couldn't convert JSON to model HYBOrderHistoryList");
    return nil;
}

return object;
}

+ (NSDictionary *)JSONKeyPathsByPropertyKey {
   return @{
@"pagination" : @"pagination",
@"orders" : @"orders",
@"sorts" : @"sorts"
};
}

+ (NSValueTransformer *)ordersJSONTransformer {
return [NSValueTransformer mtl_JSONArrayTransformerWithModelClass:[HYBOrderHistory class]];
}

+ (NSValueTransformer *)sortsJSONTransformer {
return [NSValueTransformer mtl_JSONArrayTransformerWithModelClass:[HYBSort class]];
}




+ (NSValueTransformer *)paginationJSONTransformer {
return [NSValueTransformer mtl_JSONDictionaryTransformerWithModelClass:[HYBPagination class]];
}



@end