//
// HYBOpeningSchedule.m
// [y] hybris Platform
//
// Copyright (c) 2000-2016 hybris AG
// All rights reserved.
//
// This software is the confidential and proprietary information of hybris
// ("Confidential Information"). You shall not disclose such Confidential
// Information and shall use it only in accordance with the terms of the
// license agreement you entered into with hybris.
//
// Warning:This file was auto-generated by OCC2Ojbc.
//

#import "HYBOpeningSchedule.h"
#import "NSValueTransformer+MTLPredefinedTransformerAdditions.h"

#import "HYBWeekdayOpeningDay.h"
#import "HYBSpecialOpeningDay.h"


@implementation HYBOpeningSchedule

+ (instancetype)openingScheduleWithParams:(NSDictionary*)params {

NSError *error = nil;
HYBOpeningSchedule *object = [MTLJSONAdapter modelOfClass:[HYBOpeningSchedule class] fromJSONDictionary:params error:&error];

if (error) {
    NSLog(@"Couldn't convert JSON to model HYBOpeningSchedule");
    return nil;
}

return object;
}

+ (NSDictionary *)JSONKeyPathsByPropertyKey {
   return @{
@"name" : @"name",
@"code" : @"code",
@"weekDayOpeningList" : @"weekDayOpeningList",
@"specialDayOpeningList" : @"specialDayOpeningList"
};
}

+ (NSValueTransformer *)weekDayOpeningListJSONTransformer {
return [NSValueTransformer mtl_JSONArrayTransformerWithModelClass:[HYBWeekdayOpeningDay class]];
}

+ (NSValueTransformer *)specialDayOpeningListJSONTransformer {
return [NSValueTransformer mtl_JSONArrayTransformerWithModelClass:[HYBSpecialOpeningDay class]];
}






@end