//
// HYBProductList.m
// [y] hybris Platform
//
// Copyright (c) 2000-2016 hybris AG
// All rights reserved.
//
// This software is the confidential and proprietary information of hybris
// ("Confidential Information"). You shall not disclose such Confidential
// Information and shall use it only in accordance with the terms of the
// license agreement you entered into with hybris.
//
// Warning:This file was auto-generated by OCC2Ojbc.
//

#import "HYBProductList.h"
#import "NSValueTransformer+MTLPredefinedTransformerAdditions.h"

#import "HYBProduct.h"


@implementation HYBProductList

+ (instancetype)productListWithParams:(NSDictionary*)params {

NSError *error = nil;
HYBProductList *object = [MTLJSONAdapter modelOfClass:[HYBProductList class] fromJSONDictionary:params error:&error];

if (error) {
    NSLog(@"Couldn't convert JSON to model HYBProductList");
    return nil;
}

return object;
}

+ (NSDictionary *)JSONKeyPathsByPropertyKey {
   return @{
@"catalog" : @"catalog",
@"totalPageCount" : @"totalPageCount",
@"currentPage" : @"currentPage",
@"version" : @"version",
@"products" : @"products",
@"totalProductCount" : @"totalProductCount"
};
}

+ (NSValueTransformer *)productsJSONTransformer {
return [NSValueTransformer mtl_JSONArrayTransformerWithModelClass:[HYBProduct class]];
}






@end