//
// HYBPaymentDetails.h
// [y] hybris Platform
//
// Copyright (c) 2000-2016 hybris AG
// All rights reserved.
//
// This software is the confidential and proprietary information of hybris
// ("Confidential Information"). You shall not disclose such Confidential
// Information and shall use it only in accordance with the terms of the
// license agreement you entered into with hybris.
//
// Warning:This file was auto-generated by OCC2Ojbc.
//

#import <Foundation/Foundation.h>
#import "MTLModel.h"
#import "MTLJSONAdapter.h"

@class HYBCardType;
@class HYBAddress;


@interface HYBPaymentDetails : MTLModel <MTLJSONSerializing>

@property (nonatomic) NSString *startMonth;
@property (nonatomic) BOOL saved;
@property (nonatomic) NSString *issueNumber;
@property (nonatomic) HYBCardType *cardType;
@property (nonatomic) NSString *startYear;
@property (nonatomic) NSString *expiryMonth;
@property (nonatomic) NSString *expiryYear;
@property (nonatomic) NSString *accountHolderName;
@property (nonatomic) BOOL defaultPayment;
@property (nonatomic) NSString *id;
@property (nonatomic) HYBAddress *billingAddress;
@property (nonatomic) NSString *subscriptionId;
@property (nonatomic) NSString *cardNumber;


+ (instancetype)paymentDetailsWithParams:(NSDictionary*)params;

@end