//
// HYBSopPaymentDetails.m
// [y] hybris Platform
//
// Copyright (c) 2000-2016 hybris AG
// All rights reserved.
//
// This software is the confidential and proprietary information of hybris
// ("Confidential Information"). You shall not disclose such Confidential
// Information and shall use it only in accordance with the terms of the
// license agreement you entered into with hybris.
//
// Warning:This file was auto-generated by OCC2Ojbc.
//

#import "HYBSopPaymentDetails.h"
#import "NSValueTransformer+MTLPredefinedTransformerAdditions.h"



@implementation HYBSopPaymentDetails

+ (instancetype)sopPaymentDetailsWithParams:(NSDictionary*)params {

NSError *error = nil;
HYBSopPaymentDetails *object = [MTLJSONAdapter modelOfClass:[HYBSopPaymentDetails class] fromJSONDictionary:params error:&error];

if (error) {
    NSLog(@"Couldn't convert JSON to model HYBSopPaymentDetails");
    return nil;
}

return object;
}

+ (NSDictionary *)JSONKeyPathsByPropertyKey {
   return @{
@"amount" : @"amount",
@"billTo_city" : @"billTo_city",
@"billTo_country" : @"billTo_country",
@"billTo_customerID" : @"billTo_customerID",
@"billTo_email" : @"billTo_email",
@"billTo_firstName" : @"billTo_firstName",
@"billTo_lastName" : @"billTo_lastName",
@"billTo_phoneNumber" : @"billTo_phoneNumber",
@"billTo_postalCode" : @"billTo_postalCode",
@"billTo_state" : @"billTo_state",
@"billTo_street1" : @"billTo_street1",
@"billTo_street2" : @"billTo_street2",
@"card_accountNumber" : @"card_accountNumber",
@"card_cardType" : @"card_cardType",
@"card_startMonth" : @"card_startMonth",
@"card_startYear" : @"card_startYear",
@"card_issueNumber" : @"card_issueNumber",
@"card_cvNumber" : @"card_cvNumber",
@"card_expirationMonth" : @"card_expirationMonth",
@"card_expirationYear" : @"card_expirationYear",
@"comments" : @"comments",
@"currency" : @"currency",
@"shipTo_city" : @"shipTo_city",
@"shipTo_country" : @"shipTo_country",
@"shipTo_firstName" : @"shipTo_firstName",
@"shipTo_lastName" : @"shipTo_lastName",
@"shipTo_phoneNumber" : @"shipTo_phoneNumber",
@"shipTo_postalCode" : @"shipTo_postalCode",
@"shipTo_shippingMethod" : @"shipTo_shippingMethod",
@"shipTo_state" : @"shipTo_state",
@"shipTo_street1" : @"shipTo_street1",
@"shipTo_street2" : @"shipTo_street2",
@"taxAmount" : @"taxAmount",
@"savePaymentInfo" : @"savePaymentInfo"
};
}






@end