//
// HYBStoreFinderSearchPage.m
// [y] hybris Platform
//
// Copyright (c) 2000-2016 hybris AG
// All rights reserved.
//
// This software is the confidential and proprietary information of hybris
// ("Confidential Information"). You shall not disclose such Confidential
// Information and shall use it only in accordance with the terms of the
// license agreement you entered into with hybris.
//
// Warning:This file was auto-generated by OCC2Ojbc.
//

#import "HYBStoreFinderSearchPage.h"
#import "NSValueTransformer+MTLPredefinedTransformerAdditions.h"

#import "HYBPointOfService.h"
#import "HYBSort.h"
#import "HYBPagination.h"


@implementation HYBStoreFinderSearchPage

+ (instancetype)storeFinderSearchPageWithParams:(NSDictionary*)params {

NSError *error = nil;
HYBStoreFinderSearchPage *object = [MTLJSONAdapter modelOfClass:[HYBStoreFinderSearchPage class] fromJSONDictionary:params error:&error];

if (error) {
    NSLog(@"Couldn't convert JSON to model HYBStoreFinderSearchPage");
    return nil;
}

return object;
}

+ (NSDictionary *)JSONKeyPathsByPropertyKey {
   return @{
@"stores" : @"stores",
@"sorts" : @"sorts",
@"pagination" : @"pagination",
@"locationText" : @"locationText",
@"sourceLatitude" : @"sourceLatitude",
@"sourceLongitude" : @"sourceLongitude",
@"boundNorthLatitude" : @"boundNorthLatitude",
@"boundEastLongitude" : @"boundEastLongitude",
@"boundSouthLatitude" : @"boundSouthLatitude",
@"boundWestLongitude" : @"boundWestLongitude"
};
}

+ (NSValueTransformer *)storesJSONTransformer {
return [NSValueTransformer mtl_JSONArrayTransformerWithModelClass:[HYBPointOfService class]];
}

+ (NSValueTransformer *)sortsJSONTransformer {
return [NSValueTransformer mtl_JSONArrayTransformerWithModelClass:[HYBSort class]];
}




+ (NSValueTransformer *)paginationJSONTransformer {
return [NSValueTransformer mtl_JSONDictionaryTransformerWithModelClass:[HYBPagination class]];
}



@end