//
// HYBSopPaymentDetails.h
// [y] hybris Platform
//
// Copyright (c) 2000-2016 hybris AG
// All rights reserved.
//
// This software is the confidential and proprietary information of hybris
// ("Confidential Information"). You shall not disclose such Confidential
// Information and shall use it only in accordance with the terms of the
// license agreement you entered into with hybris.
//
// Warning:This file was auto-generated by OCC2Ojbc.
//

#import <Foundation/Foundation.h>
#import "MTLModel.h"
#import "MTLJSONAdapter.h"



@interface HYBSopPaymentDetails : MTLModel <MTLJSONSerializing>

@property (nonatomic) NSString *amount;
@property (nonatomic) NSString *billTo_city;
@property (nonatomic) NSString *billTo_country;
@property (nonatomic) NSString *billTo_customerID;
@property (nonatomic) NSString *billTo_email;
@property (nonatomic) NSString *billTo_firstName;
@property (nonatomic) NSString *billTo_lastName;
@property (nonatomic) NSString *billTo_phoneNumber;
@property (nonatomic) NSString *billTo_postalCode;
@property (nonatomic) NSString *billTo_state;
@property (nonatomic) NSString *billTo_street1;
@property (nonatomic) NSString *billTo_street2;
@property (nonatomic) NSString *card_accountNumber;
@property (nonatomic) NSString *card_cardType;
@property (nonatomic) NSString *card_startMonth;
@property (nonatomic) NSString *card_startYear;
@property (nonatomic) NSString *card_issueNumber;
@property (nonatomic) NSString *card_cvNumber;
@property (nonatomic) NSString *card_expirationMonth;
@property (nonatomic) NSString *card_expirationYear;
@property (nonatomic) NSString *comments;
@property (nonatomic) NSString *currency;
@property (nonatomic) NSString *shipTo_city;
@property (nonatomic) NSString *shipTo_country;
@property (nonatomic) NSString *shipTo_firstName;
@property (nonatomic) NSString *shipTo_lastName;
@property (nonatomic) NSString *shipTo_phoneNumber;
@property (nonatomic) NSString *shipTo_postalCode;
@property (nonatomic) NSString *shipTo_shippingMethod;
@property (nonatomic) NSString *shipTo_state;
@property (nonatomic) NSString *shipTo_street1;
@property (nonatomic) NSString *shipTo_street2;
@property (nonatomic) NSString *taxAmount;
@property (nonatomic) BOOL savePaymentInfo;


+ (instancetype)sopPaymentDetailsWithParams:(NSDictionary*)params;

@end