//
// HYBUser.h
// [y] hybris Platform
//
// Copyright (c) 2000-2016 hybris AG
// All rights reserved.
//
// This software is the confidential and proprietary information of hybris
// ("Confidential Information"). You shall not disclose such Confidential
// Information and shall use it only in accordance with the terms of the
// license agreement you entered into with hybris.
//
// Warning:This file was auto-generated by OCC2Ojbc.
//

#import <Foundation/Foundation.h>
#import "MTLModel.h"
#import "MTLJSONAdapter.h"

#import "HYBPrincipal.h"

@class HYBCurrency;
@class HYBLanguage;
@class HYBAddress;


@interface HYBUser : HYBPrincipal

@property (nonatomic) NSString *firstName;
@property (nonatomic) NSString *lastName;
@property (nonatomic) NSString *displayUid;
@property (nonatomic) NSArray *roles;
@property (nonatomic) HYBCurrency *currency;
@property (nonatomic) HYBLanguage *language;
@property (nonatomic) NSString *title;
@property (nonatomic) NSString *titleCode;
@property (nonatomic) HYBAddress *defaultAddress;


+ (instancetype)userWithParams:(NSDictionary*)params;

@end