//
// HYBUserGroupList.m
// [y] hybris Platform
//
// Copyright (c) 2000-2016 hybris AG
// All rights reserved.
//
// This software is the confidential and proprietary information of hybris
// ("Confidential Information"). You shall not disclose such Confidential
// Information and shall use it only in accordance with the terms of the
// license agreement you entered into with hybris.
//
// Warning:This file was auto-generated by OCC2Ojbc.
//

#import "HYBUserGroupList.h"
#import "NSValueTransformer+MTLPredefinedTransformerAdditions.h"

#import "HYBUserGroup.h"


@implementation HYBUserGroupList

+ (instancetype)userGroupListWithParams:(NSDictionary*)params {

NSError *error = nil;
HYBUserGroupList *object = [MTLJSONAdapter modelOfClass:[HYBUserGroupList class] fromJSONDictionary:params error:&error];

if (error) {
    NSLog(@"Couldn't convert JSON to model HYBUserGroupList");
    return nil;
}

return object;
}

+ (NSDictionary *)JSONKeyPathsByPropertyKey {
   return @{
@"userGroups" : @"userGroups",
@"totalNumber" : @"totalNumber",
@"pageSize" : @"pageSize",
@"numberOfPages" : @"numberOfPages",
@"currentPage" : @"currentPage"
};
}

+ (NSValueTransformer *)userGroupsJSONTransformer {
return [NSValueTransformer mtl_JSONArrayTransformerWithModelClass:[HYBUserGroup class]];
}






@end