//
// HYBVoucher.m
// [y] hybris Platform
//
// Copyright (c) 2000-2016 hybris AG
// All rights reserved.
//
// This software is the confidential and proprietary information of hybris
// ("Confidential Information"). You shall not disclose such Confidential
// Information and shall use it only in accordance with the terms of the
// license agreement you entered into with hybris.
//
// Warning:This file was auto-generated by OCC2Ojbc.
//

#import "HYBVoucher.h"
#import "NSValueTransformer+MTLPredefinedTransformerAdditions.h"

#import "HYBCurrency.h"
#import "HYBPrice.h"


@implementation HYBVoucher

+ (instancetype)voucherWithParams:(NSDictionary*)params {

NSError *error = nil;
HYBVoucher *object = [MTLJSONAdapter modelOfClass:[HYBVoucher class] fromJSONDictionary:params error:&error];

if (error) {
    NSLog(@"Couldn't convert JSON to model HYBVoucher");
    return nil;
}

return object;
}

+ (NSDictionary *)JSONKeyPathsByPropertyKey {
   return @{
@"code" : @"code",
@"voucherCode" : @"voucherCode",
@"name" : @"name",
@"descriptor" : @"description",
@"value" : @"value",
@"valueFormatted" : @"valueFormatted",
@"valueString" : @"valueString",
@"freeShipping" : @"freeShipping",
@"currency" : @"currency",
@"appliedValue" : @"appliedValue"
};
}




+ (NSValueTransformer *)currencyJSONTransformer {
return [NSValueTransformer mtl_JSONDictionaryTransformerWithModelClass:[HYBCurrency class]];
}

+ (NSValueTransformer *)appliedValueJSONTransformer {
return [NSValueTransformer mtl_JSONDictionaryTransformerWithModelClass:[HYBPrice class]];
}



@end