//
// HYBVariantValueCategory.m
// [y] hybris Platform
//
// Copyright (c) 2000-2016 hybris AG
// All rights reserved.
//
// This software is the confidential and proprietary information of hybris
// ("Confidential Information"). You shall not disclose such Confidential
// Information and shall use it only in accordance with the terms of the
// license agreement you entered into with hybris.
//
// Warning:This file was auto-generated by OCC2Ojbc.
//

#import "HYBVariantValueCategory.h"
#import "NSValueTransformer+MTLPredefinedTransformerAdditions.h"

#import "HYBVariantCategory.h"


@implementation HYBVariantValueCategory

+ (instancetype)variantValueCategoryWithParams:(NSDictionary*)params {

NSError *error = nil;
HYBVariantValueCategory *object = [MTLJSONAdapter modelOfClass:[HYBVariantValueCategory class] fromJSONDictionary:params error:&error];

if (error) {
    NSLog(@"Couldn't convert JSON to model HYBVariantValueCategory");
    return nil;
}

return object;
}

+ (NSDictionary *)JSONKeyPathsByPropertyKey {
   return @{
@"name" : @"name",
@"sequence" : @"sequence",
@"superCategories" : @"superCategories"
};
}

+ (NSValueTransformer *)superCategoriesJSONTransformer {
return [NSValueTransformer mtl_JSONArrayTransformerWithModelClass:[HYBVariantCategory class]];
}






@end