//
// HYBVariantMatrixElement.m
// [y] hybris Platform
//
// Copyright (c) 2000-2016 hybris AG
// All rights reserved.
//
// This software is the confidential and proprietary information of hybris
// ("Confidential Information"). You shall not disclose such Confidential
// Information and shall use it only in accordance with the terms of the
// license agreement you entered into with hybris.
//
// Warning:This file was auto-generated by OCC2Ojbc.
//

#import "HYBVariantMatrixElement.h"
#import "NSValueTransformer+MTLPredefinedTransformerAdditions.h"

#import "HYBVariantValueCategory.h"
#import "HYBVariantCategory.h"
#import "HYBVariantOption.h"
#import "HYBVariantMatrixElement.h"


@implementation HYBVariantMatrixElement

+ (instancetype)variantMatrixElementWithParams:(NSDictionary*)params {

NSError *error = nil;
HYBVariantMatrixElement *object = [MTLJSONAdapter modelOfClass:[HYBVariantMatrixElement class] fromJSONDictionary:params error:&error];

if (error) {
    NSLog(@"Couldn't convert JSON to model HYBVariantMatrixElement");
    return nil;
}

return object;
}

+ (NSDictionary *)JSONKeyPathsByPropertyKey {
   return @{
@"variantValueCategory" : @"variantValueCategory",
@"parentVariantCategory" : @"parentVariantCategory",
@"variantOption" : @"variantOption",
@"elements" : @"elements",
@"isLeaf" : @"isLeaf"
};
}

+ (NSValueTransformer *)elementsJSONTransformer {
return [NSValueTransformer mtl_JSONArrayTransformerWithModelClass:[HYBVariantMatrixElement class]];
}




+ (NSValueTransformer *)variantValueCategoryJSONTransformer {
return [NSValueTransformer mtl_JSONDictionaryTransformerWithModelClass:[HYBVariantValueCategory class]];
}

+ (NSValueTransformer *)parentVariantCategoryJSONTransformer {
return [NSValueTransformer mtl_JSONDictionaryTransformerWithModelClass:[HYBVariantCategory class]];
}

+ (NSValueTransformer *)variantOptionJSONTransformer {
return [NSValueTransformer mtl_JSONDictionaryTransformerWithModelClass:[HYBVariantOption class]];
}



@end