# B2C Accelerator Compose

version: '2'

services:

  hsql:
    image: b2cacc_deployment_hsql
    volumes:
      - ./state/hsql:/opt/hsqldb/data

  solr:
    image: ybase_solr
    command: default
    volumes:
      - ./state/solr:/opt/solr/server/solr/cores

  platform_admin_init:
    image: b2cacc_deployment_platform
    command: admin initialize
    depends_on:
      - hsql
    volumes:
      - ./resources/secrets/:/etc/ssl/certs/hybris
      - ./state/media:/opt/hybris/data/media