# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'yScanTest' do
  	pod 'yScanningLibrary', :path => '../'
end

target 'yScanTestTests' do
	pod 'yScanningLibrary', :path => '../'
end

