//
// HYBAddress.m
// [y] hybris Platform
//
// Copyright (c) 2000-2016 hybris AG
// All rights reserved.
//
// This software is the confidential and proprietary information of hybris
// ("Confidential Information"). You shall not disclose such Confidential
// Information and shall use it only in accordance with the terms of the
// license agreement you entered into with hybris.
//
// Warning:This file was auto-generated by OCC2Ojbc.
//

#import "HYBAddress.h"
#import "NSValueTransformer+MTLPredefinedTransformerAdditions.h"

#import "HYBCountry.h"
#import "HYBRegion.h"


@implementation HYBAddress

+ (instancetype)addressWithParams:(NSDictionary*)params {

NSError *error = nil;
HYBAddress *object = [MTLJSONAdapter modelOfClass:[HYBAddress class] fromJSONDictionary:params error:&error];

if (error) {
    NSLog(@"Couldn't convert JSON to model HYBAddress");
    return nil;
}

return object;
}

+ (NSDictionary *)JSONKeyPathsByPropertyKey {
   return @{
@"lastName" : @"lastName",
@"country" : @"country",
@"town" : @"town",
@"companyName" : @"companyName",
@"postalCode" : @"postalCode",
@"title" : @"title",
@"titleCode" : @"titleCode",
@"firstName" : @"firstName",
@"formattedAddress" : @"formattedAddress",
@"phone" : @"phone",
@"visibleInAddressBook" : @"visibleInAddressBook",
@"shippingAddress" : @"shippingAddress",
@"id" : @"id",
@"region" : @"region",
@"line2" : @"line2",
@"line1" : @"line1",
@"email" : @"email"
};
}


+ (NSValueTransformer *)countryJSONTransformer {
return [NSValueTransformer mtl_JSONDictionaryTransformerWithModelClass:[HYBCountry class]];
}

+ (NSValueTransformer *)regionJSONTransformer {
return [NSValueTransformer mtl_JSONDictionaryTransformerWithModelClass:[HYBRegion class]];
}



@end