//
// HYBAbstractOrder.m
// [y] hybris Platform
//
// Copyright (c) 2000-2016 hybris AG
// All rights reserved.
//
// This software is the confidential and proprietary information of hybris
// ("Confidential Information"). You shall not disclose such Confidential
// Information and shall use it only in accordance with the terms of the
// license agreement you entered into with hybris.
//
// Warning:This file was auto-generated by OCC2Ojbc.
//

#import "HYBAbstractOrder.h"
#import "NSValueTransformer+MTLPredefinedTransformerAdditions.h"

#import "HYBPromotionResult.h"
#import "HYBPrice.h"
#import "HYBVoucher.h"
#import "HYBDeliveryMode.h"
#import "HYBAddress.h"
#import "HYBPickupOrderEntryGroup.h"
#import "HYBOrderEntry.h"
#import "HYBPrincipal.h"
#import "HYBPaymentDetails.h"
#import "HYBDeliveryOrderEntryGroup.h"


@implementation HYBAbstractOrder

+ (instancetype)abstractOrderWithParams:(NSDictionary*)params {

NSError *error = nil;
HYBAbstractOrder *object = [MTLJSONAdapter modelOfClass:[HYBAbstractOrder class] fromJSONDictionary:params error:&error];

if (error) {
    NSLog(@"Couldn't convert JSON to model HYBAbstractOrder");
    return nil;
}

return object;
}

+ (NSDictionary *)JSONKeyPathsByPropertyKey {
    return @{
             @"appliedProductPromotions" : @"appliedProductPromotions",
             @"code" : @"code",
             @"totalPrice" : @"totalPrice",
             @"totalDiscounts" : @"totalDiscounts",
             @"subTotal" : @"subTotal",
             @"totalTax" : @"totalTax",
             @"appliedVouchers" : @"appliedVouchers",
             @"deliveryMode" : @"deliveryMode",
             @"deliveryAddress" : @"deliveryAddress",
             @"deliveryItemsQuantity" : @"deliveryItemsQuantity",
             @"totalPriceWithTax" : @"totalPriceWithTax",
             @"net" : @"net",
             @"calculated" : @"calculated",
             @"totalItems" : @"totalItems",
             @"productDiscounts" : @"productDiscounts",
             @"appliedOrderPromotions" : @"appliedOrderPromotions",
             @"pickupOrderGroups" : @"pickupOrderGroups",
             @"orderDiscounts" : @"orderDiscounts",
             @"store" : @"store",
             @"entries" : @"entries",
             @"site" : @"site",
             @"guid" : @"guid",
             @"pickupItemsQuantity" : @"pickupItemsQuantity",
             @"user" : @"user",
             @"paymentInfo" : @"paymentInfo",
             @"deliveryOrderGroups" : @"deliveryOrderGroups",
             @"deliveryCost" : @"deliveryCost"
             };
}

+ (NSValueTransformer *)appliedProductPromotionsJSONTransformer {
    return [NSValueTransformer mtl_JSONArrayTransformerWithModelClass:[HYBPromotionResult class]];
}

+ (NSValueTransformer *)appliedVouchersJSONTransformer {
    return [NSValueTransformer mtl_JSONArrayTransformerWithModelClass:[HYBVoucher class]];
}

+ (NSValueTransformer *)appliedOrderPromotionsJSONTransformer {
    return [NSValueTransformer mtl_JSONArrayTransformerWithModelClass:[HYBPromotionResult class]];
}

+ (NSValueTransformer *)pickupOrderGroupsJSONTransformer {
    return [NSValueTransformer mtl_JSONArrayTransformerWithModelClass:[HYBPickupOrderEntryGroup class]];
}

+ (NSValueTransformer *)entriesJSONTransformer {
    return [NSValueTransformer mtl_JSONArrayTransformerWithModelClass:[HYBOrderEntry class]];
}

+ (NSValueTransformer *)deliveryOrderGroupsJSONTransformer {
    return [NSValueTransformer mtl_JSONArrayTransformerWithModelClass:[HYBDeliveryOrderEntryGroup class]];
}




+ (NSValueTransformer *)totalPriceJSONTransformer {
    return [NSValueTransformer mtl_JSONDictionaryTransformerWithModelClass:[HYBPrice class]];
}

+ (NSValueTransformer *)totalDiscountsJSONTransformer {
    return [NSValueTransformer mtl_JSONDictionaryTransformerWithModelClass:[HYBPrice class]];
}

+ (NSValueTransformer *)subTotalJSONTransformer {
    return [NSValueTransformer mtl_JSONDictionaryTransformerWithModelClass:[HYBPrice class]];
}

+ (NSValueTransformer *)totalTaxJSONTransformer {
    return [NSValueTransformer mtl_JSONDictionaryTransformerWithModelClass:[HYBPrice class]];
}

+ (NSValueTransformer *)deliveryModeJSONTransformer {
    return [NSValueTransformer mtl_JSONDictionaryTransformerWithModelClass:[HYBDeliveryMode class]];
}

+ (NSValueTransformer *)deliveryAddressJSONTransformer {
    return [NSValueTransformer mtl_JSONDictionaryTransformerWithModelClass:[HYBAddress class]];
}

+ (NSValueTransformer *)totalPriceWithTaxJSONTransformer {
    return [NSValueTransformer mtl_JSONDictionaryTransformerWithModelClass:[HYBPrice class]];
}

+ (NSValueTransformer *)productDiscountsJSONTransformer {
    return [NSValueTransformer mtl_JSONDictionaryTransformerWithModelClass:[HYBPrice class]];
}

+ (NSValueTransformer *)orderDiscountsJSONTransformer {
    return [NSValueTransformer mtl_JSONDictionaryTransformerWithModelClass:[HYBPrice class]];
}

+ (NSValueTransformer *)userJSONTransformer {
    return [NSValueTransformer mtl_JSONDictionaryTransformerWithModelClass:[HYBPrincipal class]];
}

+ (NSValueTransformer *)paymentInfoJSONTransformer {
    return [NSValueTransformer mtl_JSONDictionaryTransformerWithModelClass:[HYBPaymentDetails class]];
}

+ (NSValueTransformer *)deliveryCostJSONTransformer {
    return [NSValueTransformer mtl_JSONDictionaryTransformerWithModelClass:[HYBPrice class]];
}


@end