//
// HYBConsignmentEntry.m
// [y] hybris Platform
//
// Copyright (c) 2000-2016 hybris AG
// All rights reserved.
//
// This software is the confidential and proprietary information of hybris
// ("Confidential Information"). You shall not disclose such Confidential
// Information and shall use it only in accordance with the terms of the
// license agreement you entered into with hybris.
//
// Warning:This file was auto-generated by OCC2Ojbc.
//

#import "HYBConsignmentEntry.h"
#import "NSValueTransformer+MTLPredefinedTransformerAdditions.h"

#import "HYBOrderEntry.h"


@implementation HYBConsignmentEntry

+ (instancetype)consignmentEntryWithParams:(NSDictionary*)params {

NSError *error = nil;
HYBConsignmentEntry *object = [MTLJSONAdapter modelOfClass:[HYBConsignmentEntry class] fromJSONDictionary:params error:&error];

if (error) {
    NSLog(@"Couldn't convert JSON to model HYBConsignmentEntry");
    return nil;
}

return object;
}

+ (NSDictionary *)JSONKeyPathsByPropertyKey {
   return @{
@"orderEntry" : @"orderEntry",
@"quantity" : @"quantity",
@"shippedQuantity" : @"shippedQuantity"
};
}




+ (NSValueTransformer *)orderEntryJSONTransformer {
return [NSValueTransformer mtl_JSONDictionaryTransformerWithModelClass:[HYBOrderEntry class]];
}



@end