//
// HYBErrorList.m
// [y] hybris Platform
//
// Copyright (c) 2000-2016 hybris AG
// All rights reserved.
//
// This software is the confidential and proprietary information of hybris
// ("Confidential Information"). You shall not disclose such Confidential
// Information and shall use it only in accordance with the terms of the
// license agreement you entered into with hybris.
//
// Warning:This file was auto-generated by OCC2Ojbc.
//

#import "HYBErrorList.h"
#import "NSValueTransformer+MTLPredefinedTransformerAdditions.h"

#import "HYBError.h"


@implementation HYBErrorList

+ (instancetype)errorListWithParams:(NSDictionary*)params {

NSError *error = nil;
HYBErrorList *object = [MTLJSONAdapter modelOfClass:[HYBErrorList class] fromJSONDictionary:params error:&error];

if (error) {
    NSLog(@"Couldn't convert JSON to model HYBErrorList");
    return nil;
}

return object;
}

+ (NSDictionary *)JSONKeyPathsByPropertyKey {
   return @{
@"errors" : @"errors"
};
}

+ (NSValueTransformer *)errorsJSONTransformer {
return [NSValueTransformer mtl_JSONArrayTransformerWithModelClass:[HYBError class]];
}






@end