//
// HYBFutureStock.m
// [y] hybris Platform
//
// Copyright (c) 2000-2016 hybris AG
// All rights reserved.
//
// This software is the confidential and proprietary information of hybris
// ("Confidential Information"). You shall not disclose such Confidential
// Information and shall use it only in accordance with the terms of the
// license agreement you entered into with hybris.
//
// Warning:This file was auto-generated by OCC2Ojbc.
//

#import "HYBFutureStock.h"
#import "NSValueTransformer+MTLPredefinedTransformerAdditions.h"

#import "HYBStock.h"


@implementation HYBFutureStock

+ (instancetype)futureStockWithParams:(NSDictionary*)params {

NSError *error = nil;
HYBFutureStock *object = [MTLJSONAdapter modelOfClass:[HYBFutureStock class] fromJSONDictionary:params error:&error];

if (error) {
    NSLog(@"Couldn't convert JSON to model HYBFutureStock");
    return nil;
}

return object;
}

+ (NSDictionary *)JSONKeyPathsByPropertyKey {
   return @{
@"stock" : @"stock",
@"date" : @"date",
@"formattedDate" : @"formattedDate"
};
}




+ (NSValueTransformer *)stockJSONTransformer {
return [NSValueTransformer mtl_JSONDictionaryTransformerWithModelClass:[HYBStock class]];
}



@end