//
// HYBOrder.m
// [y] hybris Platform
//
// Copyright (c) 2000-2016 hybris AG
// All rights reserved.
//
// This software is the confidential and proprietary information of hybris
// ("Confidential Information"). You shall not disclose such Confidential
// Information and shall use it only in accordance with the terms of the
// license agreement you entered into with hybris.
//
// Warning:This file was auto-generated by OCC2Ojbc.
//

#import "HYBOrder.h"
#import "NSValueTransformer+MTLPredefinedTransformerAdditions.h"

#import "HYBOrderEntry.h"
#import "HYBConsignment.h"


@implementation HYBOrder

+ (instancetype)orderWithParams:(NSDictionary*)params {

NSError *error = nil;
HYBOrder *object = [MTLJSONAdapter modelOfClass:[HYBOrder class] fromJSONDictionary:params error:&error];

if (error) {
    NSLog(@"Couldn't convert JSON to model HYBOrder");
    return nil;
}

return object;
}

+ (NSDictionary *)JSONKeyPathsByPropertyKey {
   return @{
@"statusDisplay" : @"statusDisplay",
@"created" : @"created",
@"unconsignedEntries" : @"unconsignedEntries",
@"totalUnitCount" : @"totalUnitCount",
@"guestCustomer" : @"guestCustomer",
@"deliveryStatusDisplay" : @"deliveryStatusDisplay",
@"consignments" : @"consignments",
@"deliveryStatus" : @"deliveryStatus",
@"status" : @"status"
};
}

+ (NSValueTransformer *)unconsignedEntriesJSONTransformer {
return [NSValueTransformer mtl_JSONArrayTransformerWithModelClass:[HYBOrderEntry class]];
}

+ (NSValueTransformer *)consignmentsJSONTransformer {
return [NSValueTransformer mtl_JSONArrayTransformerWithModelClass:[HYBConsignment class]];
}






@end