//
// HYBOrderEntryGroup.m
// [y] hybris Platform
//
// Copyright (c) 2000-2016 hybris AG
// All rights reserved.
//
// This software is the confidential and proprietary information of hybris
// ("Confidential Information"). You shall not disclose such Confidential
// Information and shall use it only in accordance with the terms of the
// license agreement you entered into with hybris.
//
// Warning:This file was auto-generated by OCC2Ojbc.
//

#import "HYBOrderEntryGroup.h"
#import "NSValueTransformer+MTLPredefinedTransformerAdditions.h"

#import "HYBOrderEntry.h"
#import "HYBPrice.h"


@implementation HYBOrderEntryGroup

+ (instancetype)orderEntryGroupWithParams:(NSDictionary*)params {

NSError *error = nil;
HYBOrderEntryGroup *object = [MTLJSONAdapter modelOfClass:[HYBOrderEntryGroup class] fromJSONDictionary:params error:&error];

if (error) {
    NSLog(@"Couldn't convert JSON to model HYBOrderEntryGroup");
    return nil;
}

return object;
}

+ (NSDictionary *)JSONKeyPathsByPropertyKey {
   return @{
@"entries" : @"entries",
@"quantity" : @"quantity",
@"totalPriceWithTax" : @"totalPriceWithTax"
};
}

+ (NSValueTransformer *)entriesJSONTransformer {
return [NSValueTransformer mtl_JSONArrayTransformerWithModelClass:[HYBOrderEntry class]];
}




+ (NSValueTransformer *)totalPriceWithTaxJSONTransformer {
return [NSValueTransformer mtl_JSONDictionaryTransformerWithModelClass:[HYBPrice class]];
}



@end