//
// HYBPromotion.h
// [y] hybris Platform
//
// Copyright (c) 2000-2016 hybris AG
// All rights reserved.
//
// This software is the confidential and proprietary information of hybris
// ("Confidential Information"). You shall not disclose such Confidential
// Information and shall use it only in accordance with the terms of the
// license agreement you entered into with hybris.
//
// Warning:This file was auto-generated by OCC2Ojbc.
//

#import <Foundation/Foundation.h>
#import "MTLModel.h"
#import "MTLJSONAdapter.h"

@class HYBImage;


@interface HYBPromotion : MTLModel <MTLJSONSerializing>

@property (nonatomic) NSString *promotionType;
@property (nonatomic) NSString *code;
@property (nonatomic) NSString *endDate;
@property (nonatomic) NSString *descriptor;
@property (nonatomic) NSArray *restrictions;
@property (nonatomic) NSString *title;
@property (nonatomic) NSNumber *priority;
@property (nonatomic) BOOL enabled;
@property (nonatomic) NSArray *firedMessages;
@property (nonatomic) NSArray *couldFireMessages;
@property (nonatomic) NSString *promotionGroup;
@property (nonatomic) HYBImage *productBanner;
@property (nonatomic) NSString *startDate;


+ (instancetype)promotionWithParams:(NSDictionary*)params;

@end