//
// HYBProduct.m
// [y] hybris Platform
//
// Copyright (c) 2000-2016 hybris AG
// All rights reserved.
//
// This software is the confidential and proprietary information of hybris
// ("Confidential Information"). You shall not disclose such Confidential
// Information and shall use it only in accordance with the terms of the
// license agreement you entered into with hybris.
//
// Warning:This file was auto-generated by OCC2Ojbc.
//

#import "HYBProduct.h"
#import "NSValueTransformer+MTLPredefinedTransformerAdditions.h"

#import "HYBVariantMatrixElement.h"
#import "HYBReview.h"
#import "HYBVariantOption.h"
#import "HYBPrice.h"
#import "HYBCategory.h"
#import "HYBPromotion.h"
#import "HYBStock.h"
#import "HYBImage.h"
#import "HYBFutureStock.h"
#import "HYBClassification.h"
#import "HYBProductReference.h"
#import "HYBPriceRange.h"
#import "HYBBaseOption.h"


@implementation HYBProduct

+ (instancetype)productWithParams:(NSDictionary*)params {

    NSError *error = nil;
    HYBProduct *object = [MTLJSONAdapter modelOfClass:[HYBProduct class] fromJSONDictionary:params error:&error];

    if (error) {
        NSLog(@"Couldn't convert JSON to model HYBProduct");
        return nil;
    }

    return object;
}

+ (NSDictionary *)JSONKeyPathsByPropertyKey {
   return @{
@"availableForPickup" : @"availableForPickup",
@"volumePricesFlag" : @"volumePricesFlag",
@"purchasable" : @"purchasable",
@"code" : @"code",
@"numberOfReviews" : @"numberOfReviews",
@"variantMatrix" : @"variantMatrix",
@"descriptor" : @"description",
@"manufacturer" : @"manufacturer",
@"variantType" : @"variantType",
@"reviews" : @"reviews",
@"variantOptions" : @"variantOptions",
@"price" : @"price",
@"averageRating" : @"averageRating",
@"firstVariantImage" : @"firstVariantImage",
@"categories" : @"categories",
@"potentialPromotions" : @"potentialPromotions",
@"stock" : @"stock",
@"summary" : @"summary",
@"images" : @"images",
@"baseProduct" : @"baseProduct",
@"url" : @"url",
@"firstVariantCode" : @"firstVariantCode",
@"futureStocks" : @"futureStocks",
@"classifications" : @"classifications",
@"productReferences" : @"productReferences",
@"name" : @"name",
@"volumePrices" : @"volumePrices",
@"priceRange" : @"priceRange",
@"multidimensional" : @"multidimensional",
@"baseOptions" : @"baseOptions"
};
}

+ (NSValueTransformer *)variantMatrixJSONTransformer {
return [NSValueTransformer mtl_JSONArrayTransformerWithModelClass:[HYBVariantMatrixElement class]];
}

+ (NSValueTransformer *)reviewsJSONTransformer {
return [NSValueTransformer mtl_JSONArrayTransformerWithModelClass:[HYBReview class]];
}

+ (NSValueTransformer *)variantOptionsJSONTransformer {
return [NSValueTransformer mtl_JSONArrayTransformerWithModelClass:[HYBVariantOption class]];
}

+ (NSValueTransformer *)categoriesJSONTransformer {
return [NSValueTransformer mtl_JSONArrayTransformerWithModelClass:[HYBCategory class]];
}

+ (NSValueTransformer *)potentialPromotionsJSONTransformer {
return [NSValueTransformer mtl_JSONArrayTransformerWithModelClass:[HYBPromotion class]];
}

+ (NSValueTransformer *)imagesJSONTransformer {
return [NSValueTransformer mtl_JSONArrayTransformerWithModelClass:[HYBImage class]];
}

+ (NSValueTransformer *)futureStocksJSONTransformer {
return [NSValueTransformer mtl_JSONArrayTransformerWithModelClass:[HYBFutureStock class]];
}

+ (NSValueTransformer *)classificationsJSONTransformer {
return [NSValueTransformer mtl_JSONArrayTransformerWithModelClass:[HYBClassification class]];
}

+ (NSValueTransformer *)productReferencesJSONTransformer {
return [NSValueTransformer mtl_JSONArrayTransformerWithModelClass:[HYBProductReference class]];
}

+ (NSValueTransformer *)volumePricesJSONTransformer {
return [NSValueTransformer mtl_JSONArrayTransformerWithModelClass:[HYBPrice class]];
}

+ (NSValueTransformer *)baseOptionsJSONTransformer {
return [NSValueTransformer mtl_JSONArrayTransformerWithModelClass:[HYBBaseOption class]];
}




+ (NSValueTransformer *)priceJSONTransformer {
return [NSValueTransformer mtl_JSONDictionaryTransformerWithModelClass:[HYBPrice class]];
}

+ (NSValueTransformer *)stockJSONTransformer {
return [NSValueTransformer mtl_JSONDictionaryTransformerWithModelClass:[HYBStock class]];
}

+ (NSValueTransformer *)priceRangeJSONTransformer {
return [NSValueTransformer mtl_JSONDictionaryTransformerWithModelClass:[HYBPriceRange class]];
}

- (NSString*)firstVariantCode {
    
    if (_firstVariantCode) {
        return _firstVariantCode;
    }
    
    return _code;
}
@end