//
// HYBPointOfService.m
// [y] hybris Platform
//
// Copyright (c) 2000-2016 hybris AG
// All rights reserved.
//
// This software is the confidential and proprietary information of hybris
// ("Confidential Information"). You shall not disclose such Confidential
// Information and shall use it only in accordance with the terms of the
// license agreement you entered into with hybris.
//
// Warning:This file was auto-generated by OCC2Ojbc.
//

#import "HYBPointOfService.h"
#import "NSValueTransformer+MTLPredefinedTransformerAdditions.h"

#import "HYBOpeningSchedule.h"
#import "HYBGeoPoint.h"
#import "HYBImage.h"
#import "HYBAddress.h"


@implementation HYBPointOfService

+ (instancetype)pointOfServiceWithParams:(NSDictionary*)params {

NSError *error = nil;
HYBPointOfService *object = [MTLJSONAdapter modelOfClass:[HYBPointOfService class] fromJSONDictionary:params error:&error];

if (error) {
    NSLog(@"Couldn't convert JSON to model HYBPointOfService");
    return nil;
}

return object;
}

+ (NSDictionary *)JSONKeyPathsByPropertyKey {
   return @{
@"name" : @"name",
@"displayName" : @"displayName",
@"url" : @"url",
@"descriptor" : @"description",
@"openingHours" : @"openingHours",
@"storeContent" : @"storeContent",
@"geoPoint" : @"geoPoint",
@"formattedDistance" : @"formattedDistance",
@"distanceKm" : @"distanceKm",
@"mapIcon" : @"mapIcon",
@"address" : @"address",
@"storeImages" : @"storeImages"
};
}

+ (NSValueTransformer *)storeImagesJSONTransformer {
return [NSValueTransformer mtl_JSONArrayTransformerWithModelClass:[HYBImage class]];
}




+ (NSValueTransformer *)openingHoursJSONTransformer {
return [NSValueTransformer mtl_JSONDictionaryTransformerWithModelClass:[HYBOpeningSchedule class]];
}

+ (NSValueTransformer *)geoPointJSONTransformer {
return [NSValueTransformer mtl_JSONDictionaryTransformerWithModelClass:[HYBGeoPoint class]];
}

+ (NSValueTransformer *)mapIconJSONTransformer {
return [NSValueTransformer mtl_JSONDictionaryTransformerWithModelClass:[HYBImage class]];
}

+ (NSValueTransformer *)addressJSONTransformer {
return [NSValueTransformer mtl_JSONDictionaryTransformerWithModelClass:[HYBAddress class]];
}



@end