//
// HYBProduct.h
// [y] hybris Platform
//
// Copyright (c) 2000-2016 hybris AG
// All rights reserved.
//
// This software is the confidential and proprietary information of hybris
// ("Confidential Information"). You shall not disclose such Confidential
// Information and shall use it only in accordance with the terms of the
// license agreement you entered into with hybris.
//
// Warning:This file was auto-generated by OCC2Ojbc.
//

#import <Foundation/Foundation.h>
#import "MTLModel.h"
#import "MTLJSONAdapter.h"

@class HYBPrice;
@class HYBStock;
@class HYBPriceRange;


@interface HYBProduct : MTLModel <MTLJSONSerializing>

@property (nonatomic) BOOL availableForPickup;
@property (nonatomic) BOOL volumePricesFlag;
@property (nonatomic) BOOL purchasable;
@property (nonatomic) NSString *code;
@property (nonatomic) NSNumber *numberOfReviews;
@property (nonatomic) NSArray *variantMatrix;
@property (nonatomic) NSString *descriptor;
@property (nonatomic) NSString *manufacturer;
@property (nonatomic) NSString *variantType;
@property (nonatomic) NSArray *reviews;
@property (nonatomic) NSArray *variantOptions;
@property (nonatomic) HYBPrice *price;
@property (nonatomic) NSNumber *averageRating;
@property (nonatomic) NSString *firstVariantImage;
@property (nonatomic) NSArray *categories;
@property (nonatomic) NSArray *potentialPromotions;
@property (nonatomic) HYBStock *stock;
@property (nonatomic) NSString *summary;
@property (nonatomic) NSArray *images;
@property (nonatomic) NSString *baseProduct;
@property (nonatomic) NSString *url;
@property (nonatomic) NSString *firstVariantCode;
@property (nonatomic) NSArray *futureStocks;
@property (nonatomic) NSArray *classifications;
@property (nonatomic) NSArray *productReferences;
@property (nonatomic) NSString *name;
@property (nonatomic) NSArray *volumePrices;
@property (nonatomic) HYBPriceRange *priceRange;
@property (nonatomic) BOOL multidimensional;
@property (nonatomic) NSArray *baseOptions;


+ (instancetype)productWithParams:(NSDictionary*)params;

@end