//
// HYBPromotionResult.m
// [y] hybris Platform
//
// Copyright (c) 2000-2016 hybris AG
// All rights reserved.
//
// This software is the confidential and proprietary information of hybris
// ("Confidential Information"). You shall not disclose such Confidential
// Information and shall use it only in accordance with the terms of the
// license agreement you entered into with hybris.
//
// Warning:This file was auto-generated by OCC2Ojbc.
//

#import "HYBPromotionResult.h"
#import "NSValueTransformer+MTLPredefinedTransformerAdditions.h"


#import "HYBPromotionOrderEntryConsumed.h"
#import "HYBPromotion.h"


@implementation HYBPromotionResult

+ (instancetype)promotionResultWithParams:(NSDictionary*)params {

NSError *error = nil;
HYBPromotionResult *object = [MTLJSONAdapter modelOfClass:[HYBPromotionResult class] fromJSONDictionary:params error:&error];

if (error) {
    NSLog(@"Couldn't convert JSON to model HYBPromotionResult");
    return nil;
}

return object;
}

+ (NSDictionary *)JSONKeyPathsByPropertyKey {
   return @{
@"consumedEntries" : @"consumedEntries",
@"descriptor" : @"description",
@"promotion" : @"promotion"
};
}

+ (NSValueTransformer *)consumedEntriesJSONTransformer {
return [NSValueTransformer mtl_JSONArrayTransformerWithModelClass:[HYBPromotionOrderEntryConsumed class]];
}




+ (NSValueTransformer *)promotionJSONTransformer {
return [NSValueTransformer mtl_JSONDictionaryTransformerWithModelClass:[HYBPromotion class]];
}



@end