//
// HYBProductReferenceList.m
// [y] hybris Platform
//
// Copyright (c) 2000-2016 hybris AG
// All rights reserved.
//
// This software is the confidential and proprietary information of hybris
// ("Confidential Information"). You shall not disclose such Confidential
// Information and shall use it only in accordance with the terms of the
// license agreement you entered into with hybris.
//
// Warning:This file was auto-generated by OCC2Ojbc.
//

#import "HYBProductReferenceList.h"
#import "NSValueTransformer+MTLPredefinedTransformerAdditions.h"

#import "HYBProductReference.h"


@implementation HYBProductReferenceList

+ (instancetype)productReferenceListWithParams:(NSDictionary*)params {

NSError *error = nil;
HYBProductReferenceList *object = [MTLJSONAdapter modelOfClass:[HYBProductReferenceList class] fromJSONDictionary:params error:&error];

if (error) {
    NSLog(@"Couldn't convert JSON to model HYBProductReferenceList");
    return nil;
}

return object;
}

+ (NSDictionary *)JSONKeyPathsByPropertyKey {
   return @{
@"references" : @"references"
};
}

+ (NSValueTransformer *)referencesJSONTransformer {
return [NSValueTransformer mtl_JSONArrayTransformerWithModelClass:[HYBProductReference class]];
}






@end