//
// HYBReviewList.m
// [y] hybris Platform
//
// Copyright (c) 2000-2016 hybris AG
// All rights reserved.
//
// This software is the confidential and proprietary information of hybris
// ("Confidential Information"). You shall not disclose such Confidential
// Information and shall use it only in accordance with the terms of the
// license agreement you entered into with hybris.
//
// Warning:This file was auto-generated by OCC2Ojbc.
//

#import "HYBReviewList.h"
#import "NSValueTransformer+MTLPredefinedTransformerAdditions.h"

#import "HYBReview.h"


@implementation HYBReviewList

+ (instancetype)reviewListWithParams:(NSDictionary*)params {

NSError *error = nil;
HYBReviewList *object = [MTLJSONAdapter modelOfClass:[HYBReviewList class] fromJSONDictionary:params error:&error];

if (error) {
    NSLog(@"Couldn't convert JSON to model HYBReviewList");
    return nil;
}

return object;
}

+ (NSDictionary *)JSONKeyPathsByPropertyKey {
   return @{
@"reviews" : @"reviews"
};
}

+ (NSValueTransformer *)reviewsJSONTransformer {
return [NSValueTransformer mtl_JSONArrayTransformerWithModelClass:[HYBReview class]];
}






@end