//
// HYBRegion.m
// [y] hybris Platform
//
// Copyright (c) 2000-2016 hybris AG
// All rights reserved.
//
// This software is the confidential and proprietary information of hybris
// ("Confidential Information"). You shall not disclose such Confidential
// Information and shall use it only in accordance with the terms of the
// license agreement you entered into with hybris.
//
// Warning:This file was auto-generated by OCC2Ojbc.
//

#import "HYBRegion.h"
#import "NSValueTransformer+MTLPredefinedTransformerAdditions.h"



@implementation HYBRegion

+ (instancetype)regionWithParams:(NSDictionary*)params {

NSError *error = nil;
HYBRegion *object = [MTLJSONAdapter modelOfClass:[HYBRegion class] fromJSONDictionary:params error:&error];

if (error) {
    NSLog(@"Couldn't convert JSON to model HYBRegion");
    return nil;
}

return object;
}

+ (NSDictionary *)JSONKeyPathsByPropertyKey {
   return @{
@"isocode" : @"isocode",
@"isocodeShort" : @"isocodeShort",
@"countryIso" : @"countryIso",
@"name" : @"name"
};
}






@end