//
// HYBSaveCartResult.m
// [y] hybris Platform
//
// Copyright (c) 2000-2016 hybris AG
// All rights reserved.
//
// This software is the confidential and proprietary information of hybris
// ("Confidential Information"). You shall not disclose such Confidential
// Information and shall use it only in accordance with the terms of the
// license agreement you entered into with hybris.
//
// Warning:This file was auto-generated by OCC2Ojbc.
//

#import "HYBSaveCartResult.h"
#import "NSValueTransformer+MTLPredefinedTransformerAdditions.h"

#import "HYBCart.h"


@implementation HYBSaveCartResult

+ (instancetype)saveCartResultWithParams:(NSDictionary*)params {

NSError *error = nil;
HYBSaveCartResult *object = [MTLJSONAdapter modelOfClass:[HYBSaveCartResult class] fromJSONDictionary:params error:&error];

if (error) {
    NSLog(@"Couldn't convert JSON to model HYBSaveCartResult");
    return nil;
}

return object;
}

+ (NSDictionary *)JSONKeyPathsByPropertyKey {
   return @{
@"savedCartData" : @"savedCartData"
};
}




+ (NSValueTransformer *)savedCartDataJSONTransformer {
return [NSValueTransformer mtl_JSONDictionaryTransformerWithModelClass:[HYBCart class]];
}



@end