//
// HYBUserGroup.m
// [y] hybris Platform
//
// Copyright (c) 2000-2016 hybris AG
// All rights reserved.
//
// This software is the confidential and proprietary information of hybris
// ("Confidential Information"). You shall not disclose such Confidential
// Information and shall use it only in accordance with the terms of the
// license agreement you entered into with hybris.
//
// Warning:This file was auto-generated by OCC2Ojbc.
//

#import "HYBUserGroup.h"
#import "NSValueTransformer+MTLPredefinedTransformerAdditions.h"

#import "HYBPrincipal.h"
#import "HYBUserGroup.h"


@implementation HYBUserGroup

+ (instancetype)userGroupWithParams:(NSDictionary*)params {

NSError *error = nil;
HYBUserGroup *object = [MTLJSONAdapter modelOfClass:[HYBUserGroup class] fromJSONDictionary:params error:&error];

if (error) {
    NSLog(@"Couldn't convert JSON to model HYBUserGroup");
    return nil;
}

return object;
}

+ (NSDictionary *)JSONKeyPathsByPropertyKey {
   return @{
@"members" : @"members",
@"subGroups" : @"subGroups",
@"membersCount" : @"membersCount"
};
}

+ (NSValueTransformer *)membersJSONTransformer {
return [NSValueTransformer mtl_JSONArrayTransformerWithModelClass:[HYBPrincipal class]];
}

+ (NSValueTransformer *)subGroupsJSONTransformer {
return [NSValueTransformer mtl_JSONArrayTransformerWithModelClass:[HYBUserGroup class]];
}






@end