//
// HYBVariantOptionQualifier.h
// [y] hybris Platform
//
// Copyright (c) 2000-2016 hybris AG
// All rights reserved.
//
// This software is the confidential and proprietary information of hybris
// ("Confidential Information"). You shall not disclose such Confidential
// Information and shall use it only in accordance with the terms of the
// license agreement you entered into with hybris.
//
// Warning:This file was auto-generated by OCC2Ojbc.
//

#import <Foundation/Foundation.h>
#import "MTLModel.h"
#import "MTLJSONAdapter.h"

@class HYBImage;


@interface HYBVariantOptionQualifier : MTLModel <MTLJSONSerializing>

@property (nonatomic) NSString *qualifier;
@property (nonatomic) NSString *name;
@property (nonatomic) NSString *value;
@property (nonatomic) HYBImage *image;


+ (instancetype)variantOptionQualifierWithParams:(NSDictionary*)params;

@end